stages:
  - deploy

deploy_app:
  stage: deploy
  only:
    - develop
  before_script:
    # Iniciamos el agente SSH y cargamos la llave privada
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    # Configuramos SSH para que no pida confirmación manual y le damos permisos estrictos
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - chmod 600 ~/.ssh/config
  script:
    - echo "Iniciando despliegue en la VM $SERVER_IP..."
    - ssh $SERVER_USER@$SERVER_IP "cd /opt/dotacion-rrhh && git pull origin desarrollo-back && docker-compose up -d --build app"
    - echo "¡Despliegue finalizado con éxito!"
