process.env.NODE_ENV = 'test';
process.env.ADMIN_ENABLED = 'false';
process.env.DB_DIALECT = 'sqljs';
process.env.DB_HOST = '';
process.env.DB_PORT = '';
process.env.DB_USER = '';
process.env.DB_PASSWORD = '';
process.env.DB_NAME = '';
process.env.AUTH_MODE = process.env.AUTH_MODE || 'db';
process.env.AUTH_COOKIES = 'true';
process.env.JWT_SECRET = process.env.JWT_SECRET || 'test-secret-key-for-jest-at-least-32-chars-long';
require('reflect-metadata');
